// GENERATED by app/scripts/build-figma-tokens.mjs — do not edit.
// Edit src/tokens/*.css, src/icons/paths.js or figma-plugin/runtime.js, then npm run figma:tokens.

const TOKENS = {
  "palette": {
    "c-ball": "#C8FF4D",
    "c-ball-glow": "#D9FF85",
    "c-ball-deep": "#9FE63A",
    "c-ball-olive": "#4D7A00",
    "c-court": "#7BD389",
    "c-court-deep": "#4FA364",
    "c-moss": "#2F5A3A",
    "c-clay": "#FF7B5C",
    "c-clay-deep": "#B8432B",
    "c-shadow": "#1B2A1A",
    "c-shadow-2": "#243523",
    "c-base": "#0A1208",
    "c-base-2": "#0E1A0C",
    "c-linen": "#F4FFE6",
    "c-ink": "#1A1A1F",
    "c-ink-2": "#3A3A40",
    "c-slate": "#4A4A52",
    "c-slate-2": "#2C2C33",
    "c-gray": "#6E6E76",
    "c-paper": "#F4F4F1",
    "c-paper-2": "#ECECE7",
    "c-paper-3": "#DCDCD6",
    "c-warn-d": "#FFC46B",
    "c-info-d": "#7BD3FF",
    "c-warn-l": "#8F5A00",
    "c-info-l": "#1668A8",
    "c-btc": "#F7931A",
    "c-eth": "#627EEA",
    "c-usdt": "#26A17B",
    "c-sol": "#14F195",
    "c-bnb": "#F3BA2F",
    "c-white": "#FFFFFF",
    "c-chip-gold": "#D4AF6A",
    "c-chip-gold-deep": "#8A6F3A",
    "c-chip-highlight": "rgba(255, 255, 255, .35)",
    "c-chip-groove": "rgba(0, 0, 0, .28)",
    "c-card-dark-bg": "linear-gradient(135deg, #1B2A1A 0%, #2F5A3A 58%, #0A1208 100%)",
    "c-card-light-bg": "linear-gradient(135deg, #F4F4F1 0%, #DCDCD6 60%, #C9C9C2 100%)",
    "c-card-shadow": "0 18px 40px -10px rgba(0, 0, 0, .5), inset 0 1px 0 rgba(255, 255, 255, .08)",
    "c-card-shadow-light": "0 18px 40px -14px rgba(26, 26, 31, .32), inset 0 1px 0 rgba(255, 255, 255, .9)",
    "c-card-glow-dark": "radial-gradient(closest-side, rgba(200, 255, 77, .22), transparent)",
    "c-card-glow-light": "radial-gradient(closest-side, rgba(255, 255, 255, .85), transparent)",
    "c-card-glow-glass": "radial-gradient(closest-side, rgba(255, 255, 255, .18), transparent)",
    "c-card-veil": "rgba(10, 18, 8, .62)"
  },
  "scale": {
    "space-0": "0px",
    "space-2": "2px",
    "space-4": "4px",
    "space-6": "6px",
    "space-8": "8px",
    "space-12": "12px",
    "space-16": "16px",
    "space-20": "20px",
    "space-24": "24px",
    "space-32": "32px",
    "space-40": "40px",
    "space-48": "48px",
    "space-64": "64px",
    "r-xs": "6px",
    "r-sm": "10px",
    "r-md": "14px",
    "r-lg": "18px",
    "r-xl": "24px",
    "r-2xl": "32px",
    "r-full": "999px",
    "r-phone": "44px",
    "control-xs": "24px",
    "control-sm": "32px",
    "control-md": "40px",
    "control-lg": "48px",
    "control-xl": "56px",
    "icon-2xs": "14px",
    "icon-xs": "16px",
    "icon-sm": "20px",
    "icon-md": "24px",
    "icon-lg": "32px",
    "touch-min": "44px",
    "screen-w": "390px",
    "screen-h": "844px",
    "statusbar-h": "54px",
    "appbar-h": "56px",
    "tabbar-h": "64px",
    "home-indicator-h": "34px",
    "font-sans": "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif",
    "font-display": "'Space Grotesk', 'Inter', system-ui, sans-serif",
    "font-mono": "ui-monospace, 'SF Mono', 'Cascadia Code', Consolas, monospace",
    "text-display-size": "40px",
    "text-display-lh": "44px",
    "text-display-w": "700",
    "text-display-ls": "-0.8px",
    "text-h1-size": "32px",
    "text-h1-lh": "36px",
    "text-h1-w": "700",
    "text-h1-ls": "-0.6px",
    "text-h2-size": "24px",
    "text-h2-lh": "28px",
    "text-h2-w": "700",
    "text-h2-ls": "-0.3px",
    "text-h3-size": "20px",
    "text-h3-lh": "24px",
    "text-h3-w": "600",
    "text-h3-ls": "-0.2px",
    "text-title-size": "17px",
    "text-title-lh": "22px",
    "text-title-w": "600",
    "text-title-ls": "0px",
    "text-body-size": "15px",
    "text-body-lh": "20px",
    "text-body-w": "400",
    "text-body-ls": "0px",
    "text-bodysm-size": "13px",
    "text-bodysm-lh": "18px",
    "text-bodysm-w": "400",
    "text-bodysm-ls": "0px",
    "text-label-size": "13px",
    "text-label-lh": "16px",
    "text-label-w": "600",
    "text-label-ls": "0.1px",
    "text-caption-size": "11px",
    "text-caption-lh": "14px",
    "text-caption-w": "500",
    "text-caption-ls": "0.2px",
    "text-mono-size": "13px",
    "text-mono-lh": "18px",
    "text-mono-w": "500",
    "text-mono-ls": "0px",
    "dur-instant": "80ms",
    "dur-fast": "140ms",
    "dur-base": "220ms",
    "dur-slow": "320ms",
    "ease-out": "cubic-bezier(.2, .8, .2, 1)",
    "ease-in-out": "cubic-bezier(.4, 0, .2, 1)",
    "ease-spring": "cubic-bezier(.34, 1.56, .64, 1)",
    "icon-stroke": "1.75"
  },
  "dark": {
    "bg-canvas": "var(--c-base)",
    "bg-surface-1": "rgba(244, 255, 230, .04)",
    "bg-surface-2": "rgba(244, 255, 230, .06)",
    "bg-surface-3": "rgba(244, 255, 230, .10)",
    "bg-inverse": "var(--c-linen)",
    "bg-overlay": "rgba(5, 8, 4, .72)",
    "bg-ambient": "radial-gradient(1200px 700px at 18% -10%, rgba(123, 211, 137, .20), transparent 60%), radial-gradient(900px 600px at 110% 30%, rgba(200, 255, 77, .10), transparent 65%), var(--c-base)",
    "fg-default": "var(--c-linen)",
    "fg-dim": "rgba(244, 255, 230, .68)",
    "fg-faint": "rgba(244, 255, 230, .42)",
    "fg-inverse": "var(--c-base)",
    "fg-accent": "var(--c-ball)",
    "fg-on-accent": "var(--c-base)",
    "border-subtle": "rgba(244, 255, 230, .10)",
    "border-strong": "rgba(244, 255, 230, .22)",
    "border-focus": "var(--c-ball)",
    "accent": "var(--c-ball)",
    "accent-hover": "var(--c-ball-glow)",
    "accent-press": "var(--c-ball-deep)",
    "accent-subtle": "rgba(200, 255, 77, .14)",
    "accent-border": "rgba(200, 255, 77, .28)",
    "success": "var(--c-ball)",
    "success-subtle": "rgba(200, 255, 77, .14)",
    "danger": "var(--c-clay)",
    "danger-subtle": "rgba(255, 123, 92, .14)",
    "warning": "var(--c-warn-d)",
    "warning-subtle": "rgba(255, 196, 107, .14)",
    "info": "var(--c-info-d)",
    "info-subtle": "rgba(123, 211, 255, .14)",
    "up": "var(--c-ball)",
    "down": "var(--c-clay)",
    "btn-primary-bg": "var(--c-ball)",
    "btn-primary-fg": "var(--c-base)",
    "btn-primary-hover": "var(--c-ball-glow)",
    "btn-primary-press": "var(--c-ball-deep)",
    "btn-secondary-bg": "rgba(244, 255, 230, .10)",
    "btn-secondary-fg": "var(--c-linen)",
    "btn-secondary-hover": "rgba(244, 255, 230, .16)",
    "btn-secondary-press": "rgba(244, 255, 230, .06)",
    "shadow-0": "none",
    "shadow-1": "0 1px 2px rgba(0, 0, 0, .30)",
    "shadow-2": "0 4px 12px rgba(0, 0, 0, .35)",
    "shadow-3": "0 12px 32px rgba(0, 0, 0, .45)",
    "shadow-4": "0 24px 64px rgba(0, 0, 0, .55)",
    "shadow-accent": "0 8px 28px rgba(200, 255, 77, .22)",
    "phone-bezel": "linear-gradient(160deg, #0E1A0C 0%, #16241A 100%)",
    "phone-screen": "linear-gradient(180deg, #0E1A0C 0%, #1B2A1A 100%)",
    "card-bg": "linear-gradient(135deg, #1B2A1A 0%, #2F5A3A 60%, #0A1208 100%)",
    "card-glow": "rgba(200, 255, 77, .22)",
    "glass-bg": "rgba(244, 255, 230, .07)",
    "glass-border": "rgba(244, 255, 230, .14)",
    "glass-blur": "20px",
    "control-thumb": "var(--c-white)",
    "control-track-off": "var(--bg-surface-3)",
    "control-track-on": "var(--accent)"
  },
  "light": {
    "bg-canvas": "var(--c-paper-2)",
    "bg-surface-1": "rgba(255, 255, 255, .72)",
    "bg-surface-2": "#FFFFFF",
    "bg-surface-3": "var(--c-paper)",
    "bg-inverse": "var(--c-ink)",
    "bg-overlay": "rgba(26, 26, 31, .48)",
    "bg-ambient": "radial-gradient(1200px 700px at 18% -10%, rgba(255, 255, 255, .95), transparent 60%), radial-gradient(900px 600px at 110% 30%, rgba(180, 180, 175, .35), transparent 65%), linear-gradient(160deg, #F4F4F1 0%, #DCDCD6 100%)",
    "fg-default": "var(--c-ink)",
    "fg-dim": "rgba(26, 26, 31, .66)",
    "fg-faint": "rgba(26, 26, 31, .40)",
    "fg-inverse": "var(--c-paper)",
    "fg-accent": "var(--c-ink)",
    "fg-on-accent": "var(--c-paper)",
    "border-subtle": "rgba(26, 26, 31, .10)",
    "border-strong": "rgba(26, 26, 31, .20)",
    "border-focus": "var(--c-ink)",
    "accent": "var(--c-ink)",
    "accent-hover": "var(--c-ink-2)",
    "accent-press": "var(--c-slate-2)",
    "accent-subtle": "rgba(26, 26, 31, .07)",
    "accent-border": "rgba(26, 26, 31, .16)",
    "success": "var(--c-ball-olive)",
    "success-subtle": "rgba(77, 122, 0, .12)",
    "danger": "var(--c-clay-deep)",
    "danger-subtle": "rgba(184, 67, 43, .12)",
    "warning": "var(--c-warn-l)",
    "warning-subtle": "rgba(143, 90, 0, .12)",
    "info": "var(--c-info-l)",
    "info-subtle": "rgba(22, 104, 168, .12)",
    "up": "var(--c-ball-olive)",
    "down": "var(--c-clay-deep)",
    "btn-primary-bg": "var(--c-ink)",
    "btn-primary-fg": "var(--c-paper)",
    "btn-primary-hover": "var(--c-ink-2)",
    "btn-primary-press": "var(--c-slate-2)",
    "btn-secondary-bg": "rgba(26, 26, 31, .07)",
    "btn-secondary-fg": "var(--c-ink)",
    "btn-secondary-hover": "rgba(26, 26, 31, .12)",
    "btn-secondary-press": "rgba(26, 26, 31, .04)",
    "shadow-0": "none",
    "shadow-1": "0 1px 2px rgba(26, 26, 31, .06)",
    "shadow-2": "0 4px 12px rgba(26, 26, 31, .08)",
    "shadow-3": "0 12px 32px rgba(26, 26, 31, .12)",
    "shadow-4": "0 24px 64px rgba(26, 26, 31, .16)",
    "shadow-accent": "0 8px 28px rgba(26, 26, 31, .18)",
    "phone-bezel": "linear-gradient(160deg, #3A3A40 0%, #15151A 100%)",
    "phone-screen": "linear-gradient(180deg, #F8F8F4 0%, #ECECE7 50%, #DCDCD6 100%)",
    "card-bg": "linear-gradient(135deg, #1A1A1F 0%, #3A3A40 60%, #15151A 100%)",
    "card-glow": "rgba(200, 200, 200, .25)",
    "glass-bg": "rgba(255, 255, 255, .62)",
    "glass-border": "rgba(255, 255, 255, .85)",
    "glass-blur": "20px",
    "control-thumb": "var(--c-white)",
    "control-track-off": "rgba(26, 26, 31, .16)",
    "control-track-on": "var(--accent)"
  }
};

const ICON_PACKS = ["navigation","wallet","status","security","settings","assets"];
const ICONS = [
 {
  "name": "home",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.5 10.6 12 3.8l8.5 6.8V19a2 2 0 0 1-2 2h-3.2v-6.2H8.7V21H5.5a2 2 0 0 1-2-2v-8.4Z\"/></svg>"
 },
 {
  "name": "card",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"3\" y=\"5.5\" width=\"18\" height=\"13\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3 10h18M6.5 14.5h3.5\"/></svg>"
 },
 {
  "name": "swap",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6 8.5h13l-3.6-3.6M18 15.5H5l3.6 3.6\"/></svg>"
 },
 {
  "name": "scan",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 9V6.5A2.5 2.5 0 0 1 6.5 4H9M15 4h2.5A2.5 2.5 0 0 1 20 6.5V9M20 15v2.5a2.5 2.5 0 0 1-2.5 2.5H15M9 20H6.5A2.5 2.5 0 0 1 4 17.5V15M3.5 12h17\"/></svg>"
 },
 {
  "name": "more",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"5\" cy=\"12\" r=\"1.6\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"1.6\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"19\" cy=\"12\" r=\"1.6\"/></svg>"
 },
 {
  "name": "menu",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 7h16M4 12h16M4 17h16\"/></svg>"
 },
 {
  "name": "close",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6.5 6.5l11 11M17.5 6.5l-11 11\"/></svg>"
 },
 {
  "name": "chevron-left",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M14.5 5.5 8 12l6.5 6.5\"/></svg>"
 },
 {
  "name": "chevron-right",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9.5 5.5 16 12l-6.5 6.5\"/></svg>"
 },
 {
  "name": "chevron-up",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M5.5 14.5 12 8l6.5 6.5\"/></svg>"
 },
 {
  "name": "chevron-down",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M5.5 9.5 12 16l6.5-6.5\"/></svg>"
 },
 {
  "name": "arrow-left",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20 12H4m6-6-6 6 6 6\"/></svg>"
 },
 {
  "name": "arrow-right",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 12h16m-6-6 6 6-6 6\"/></svg>"
 },
 {
  "name": "arrow-up",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 20V4m-6 6 6-6 6 6\"/></svg>"
 },
 {
  "name": "arrow-down",
  "pack": "navigation",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 4v16m6-6-6 6-6-6\"/></svg>"
 },
 {
  "name": "send",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M7 17 17 7M8.5 7H17v8.5\"/></svg>"
 },
 {
  "name": "receive",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M17 7 7 17M15.5 17H7V8.5\"/></svg>"
 },
 {
  "name": "buy",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 8v8M8 12h8\"/></svg>"
 },
 {
  "name": "stake",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3.2 3.5 7.6 12 12l8.5-4.4L12 3.2ZM3.5 12 12 16.4 20.5 12M3.5 16.4 12 20.8l8.5-4.4\"/></svg>"
 },
 {
  "name": "pay",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"2.5\" y=\"6\" width=\"14\" height=\"12\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M2.5 10h14M19 9.2a4 4 0 0 1 0 5.6M21.3 7.2a7 7 0 0 1 0 9.6\"/></svg>"
 },
 {
  "name": "qr",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"3.5\" y=\"3.5\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"13.5\" y=\"3.5\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"3.5\" y=\"13.5\" width=\"7\" height=\"7\" rx=\"1.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M13.5 13.5h3v3h-3zM20.5 20.5h-3v-3\"/></svg>"
 },
 {
  "name": "copy",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"8.5\" y=\"8.5\" width=\"12\" height=\"12\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M5.5 15.5h-.5a1.5 1.5 0 0 1-1.5-1.5V5a1.5 1.5 0 0 1 1.5-1.5h9A1.5 1.5 0 0 1 15.5 5v.5\"/></svg>"
 },
 {
  "name": "share",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 15.5V3.5m0 0L8.2 7.3M12 3.5l3.8 3.8M4.5 13.5V19a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2v-5.5\"/></svg>"
 },
 {
  "name": "eye",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12Z\"/><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"3\"/></svg>"
 },
 {
  "name": "eye-off",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 4l16 16M9.9 9.9A3 3 0 0 0 14.1 14.1M6.3 6.6C4 8.2 2.5 12 2.5 12s3.5 6.5 9.5 6.5c1.7 0 3.2-.5 4.5-1.2M18.4 15.1c1.9-1.6 3.1-3.1 3.1-3.1S18 5.5 12 5.5c-.8 0-1.6.1-2.3.3\"/></svg>"
 },
 {
  "name": "plus",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 4.5v15M4.5 12h15\"/></svg>"
 },
 {
  "name": "minus",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 12h15\"/></svg>"
 },
 {
  "name": "filter",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 6.5h16M7 12h10M10 17.5h4\"/></svg>"
 },
 {
  "name": "search",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"11\" cy=\"11\" r=\"6.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15.8 15.8 20.5 20.5\"/></svg>"
 },
 {
  "name": "refresh",
  "pack": "wallet",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.5 12a8.5 8.5 0 1 1-2.5-6M20.5 3.5v5h-5\"/></svg>"
 },
 {
  "name": "check",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M5 12.5 9.5 17 19 7\"/></svg>"
 },
 {
  "name": "check-circle",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8 12.2 10.8 15 16 9.5\"/></svg>"
 },
 {
  "name": "alert-triangle",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3.8 2.9 19.5a1 1 0 0 0 .9 1.5h16.4a1 1 0 0 0 .9-1.5L12 3.8Z\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 9.5v4.2\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"17.2\" r=\"0.9\"/></svg>"
 },
 {
  "name": "alert-circle",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 7.5v5\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"16.3\" r=\"0.9\"/></svg>"
 },
 {
  "name": "info",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 11v5.5\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"7.7\" r=\"0.9\"/></svg>"
 },
 {
  "name": "clock",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 7v5.2l3.2 2\"/></svg>"
 },
 {
  "name": "spinner",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3.5a8.5 8.5 0 1 0 8.5 8.5\"/></svg>"
 },
 {
  "name": "x-circle",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9.2 9.2l5.6 5.6M14.8 9.2l-5.6 5.6\"/></svg>"
 },
 {
  "name": "shield",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3.2 5 6.2v5.6c0 4 2.8 7.6 7 9.1 4.2-1.5 7-5.1 7-9.1V6.2l-7-3Z\"/></svg>"
 },
 {
  "name": "lock",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"4.5\" y=\"10.5\" width=\"15\" height=\"10\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8 10.5V7.8a4 4 0 0 1 8 0v2.7\"/></svg>"
 },
 {
  "name": "unlock",
  "pack": "status",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"4.5\" y=\"10.5\" width=\"15\" height=\"10\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8 10.5V7.8a4 4 0 0 1 7.4-2.1\"/></svg>"
 },
 {
  "name": "face-id",
  "pack": "security",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 8.5V6.5A2.5 2.5 0 0 1 6.5 4h2M15.5 4h2A2.5 2.5 0 0 1 20 6.5v2M20 15.5v2a2.5 2.5 0 0 1-2.5 2.5h-2M8.5 20h-2A2.5 2.5 0 0 1 4 17.5v-2M9 10v1.5M15 10v1.5M12 10v3.5h-1M9.5 16a3.5 3.5 0 0 0 5 0\"/></svg>"
 },
 {
  "name": "touch-id",
  "pack": "security",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 4.5a7.5 7.5 0 0 0-7.5 7.5v2M19.5 12a7.5 7.5 0 0 0-3.6-6.4M8.5 19.4A7.5 7.5 0 0 1 8 12a4 4 0 0 1 8 0v2.5M19.4 16.5a7.6 7.6 0 0 1-.9 2.4M12 12v3a4 4 0 0 0 1.2 2.9M15.6 20.3a7.6 7.6 0 0 0 1.5-1.6\"/></svg>"
 },
 {
  "name": "pin",
  "pack": "security",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2.5\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"8.5\" cy=\"10\" r=\"1.2\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"10\" r=\"1.2\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"15.5\" cy=\"10\" r=\"1.2\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8.5 14.5h7\"/></svg>"
 },
 {
  "name": "key",
  "pack": "security",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"8\" cy=\"8\" r=\"4\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M10.9 10.9 20 20M17 17l-2 2M14 14l-2 2\"/></svg>"
 },
 {
  "name": "seed",
  "pack": "security",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 21c0-5 3-9 8-10-1 5-3.5 8-8 10ZM12 21c0-5-3-9-8-10 1 5 3.5 8 8 10ZM12 21v-6.5\"/></svg>"
 },
 {
  "name": "settings",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"3.2\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 2.5v2.8M12 18.7v2.8M21.5 12h-2.8M5.3 12H2.5M18.7 5.3l-2 2M7.3 16.7l-2 2M18.7 18.7l-2-2M7.3 7.3l-2-2\"/></svg>"
 },
 {
  "name": "bell",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M18 9.5a6 6 0 1 0-12 0c0 6-2.5 7.5-2.5 7.5h17S18 15.5 18 9.5ZM10.2 20.5a2.2 2.2 0 0 0 3.6 0\"/></svg>"
 },
 {
  "name": "globe",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M3.5 12h17M12 3.5c2.2 2.3 3.4 5.3 3.4 8.5S14.2 18.2 12 20.5c-2.2-2.3-3.4-5.3-3.4-8.5S9.8 5.8 12 3.5Z\"/></svg>"
 },
 {
  "name": "moon",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.5 13.2A8.5 8.5 0 1 1 10.8 3.5a6.5 6.5 0 0 0 9.7 9.7Z\"/></svg>"
 },
 {
  "name": "sun",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"4\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 2.5v2.2M12 19.3v2.2M21.5 12h-2.2M4.7 12H2.5M18.7 5.3l-1.5 1.5M6.8 17.2l-1.5 1.5M18.7 18.7l-1.5-1.5M6.8 6.8 5.3 5.3\"/></svg>"
 },
 {
  "name": "user",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"8.5\" r=\"4\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4.5 20.5a7.5 7.5 0 0 1 15 0\"/></svg>"
 },
 {
  "name": "help",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><circle fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"12\" r=\"8.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9.5 9.6a2.6 2.6 0 1 1 3.4 2.5c-.6.2-.9.8-.9 1.4v.6\"/><circle fill=\"#000000\" stroke=\"none\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" cx=\"12\" cy=\"16.8\" r=\"0.9\"/></svg>"
 },
 {
  "name": "logout",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15.5 16.5 20 12l-4.5-4.5M20 12H9M13 3.5H6.5a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2H13\"/></svg>"
 },
 {
  "name": "trash",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 6.5h16M9.5 6.5V5a1.5 1.5 0 0 1 1.5-1.5h2A1.5 1.5 0 0 1 14.5 5v1.5M6.5 6.5l.9 13.1a1.5 1.5 0 0 0 1.5 1.4h6.2a1.5 1.5 0 0 0 1.5-1.4l.9-13.1M10 10.5v6M14 10.5v6\"/></svg>"
 },
 {
  "name": "edit",
  "pack": "settings",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M4 20h4L19.3 8.7a2.1 2.1 0 0 0-3-3L5 17v3ZM15.5 6.5l3 3\"/></svg>"
 },
 {
  "name": "btc",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"#000000\" stroke=\"none\" d=\"M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm3.6 8.6c-.2.9-.8 1.3-1.6 1.4.9.2 1.4.9 1.3 2-.2 1.4-1.2 2-2.8 2.1v1.7h-1.2v-1.6h-1v1.6H9.1v-1.7H7v-1.3h.6c.4 0 .5-.2.5-.5V9.3c0-.4-.2-.6-.6-.6H7V7.4h2.1V5.8h1.2v1.5h1V5.8h1.2v1.6c1.5.1 2.4.7 2.5 1.9Zm-4.5.9h1.1c.7 0 1.2-.3 1.2-.9s-.4-.9-1.2-.9h-1.1v1.8Zm0 3.4h1.4c.8 0 1.3-.3 1.3-1s-.5-1-1.3-1h-1.4v2Z\"/></svg>"
 },
 {
  "name": "eth",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"#000000\" stroke=\"none\" d=\"M12 2.5 5.6 12.4 12 16.1l6.4-3.7L12 2.5ZM5.6 13.7 12 22l6.4-8.3L12 17.4l-6.4-3.7Z\"/></svg>"
 },
 {
  "name": "usdt",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"#000000\" stroke=\"none\" d=\"M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM6.8 7.3h10.4v2.4h-3.9v1.1c2.6.1 4.6.6 4.6 1.3 0 .7-2.2 1.3-5 1.3s-5-.6-5-1.3c0-.6 1.9-1.2 4.4-1.3v-1.1H6.8V7.3Zm5.2 6.9c2.9 0 5.3-.5 5.9-1.2v.9c0 .9-2.6 1.6-5.9 1.6s-5.9-.7-5.9-1.6V13c.6.7 3 1.2 5.9 1.2Zm-1.2 1.9h2.4v1.9h-2.4v-1.9Z\"/></svg>"
 },
 {
  "name": "sol",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"#000000\" stroke=\"none\" d=\"M6.4 15.6a.7.7 0 0 1 .5-.2h13.2c.4 0 .6.5.3.8l-2.8 2.8a.7.7 0 0 1-.5.2H3.9c-.4 0-.6-.5-.3-.8l2.8-2.8ZM6.4 5.2a.7.7 0 0 1 .5-.2h13.2c.4 0 .6.5.3.8l-2.8 2.8a.7.7 0 0 1-.5.2H3.9c-.4 0-.6-.5-.3-.8l2.8-2.8ZM17.6 10.4a.7.7 0 0 0-.5-.2H3.9c-.4 0-.6.5-.3.8l2.8 2.8c.1.1.3.2.5.2h13.2c.4 0 .6-.5.3-.8l-2.8-2.8Z\"/></svg>"
 },
 {
  "name": "bnb",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"#000000\" stroke=\"none\" d=\"M12 2.5 8.1 6.4l1.9 1.9L12 6.3l2 2 1.9-1.9L12 2.5ZM5.6 8.9 3.7 10.8l1.9 1.9 1.9-1.9-1.9-1.9Zm12.8 0-1.9 1.9 1.9 1.9 1.9-1.9-1.9-1.9ZM12 9.6l-2.4 2.4 2.4 2.4 2.4-2.4L12 9.6Zm-3.9 3.7-1.9 1.9L12 21.5l5.8-6.3-1.9-1.9-2 2-1.9 1.9-1.9-1.9-2-2Z\"/></svg>"
 },
 {
  "name": "chip",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"4\" y=\"6.5\" width=\"16\" height=\"11\" rx=\"2.5\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9 6.5v11M15 6.5v11M4 10.5h5M15 10.5h5M4 13.5h5M15 13.5h5\"/></svg>"
 },
 {
  "name": "contactless",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M8.5 8.2a5.5 5.5 0 0 1 0 7.6M12 5.6a9 9 0 0 1 0 12.8M15.5 3a12.5 12.5 0 0 1 0 18\"/></svg>"
 },
 {
  "name": "nfc",
  "pack": "assets",
  "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\"><rect fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" x=\"3.5\" y=\"3.5\" width=\"17\" height=\"17\" rx=\"4\"/><path fill=\"none\" stroke=\"#000000\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M9 15V9.5c0-1.7 1.3-3 3-3s3 1.3 3 3M12 9.5V15\"/></svg>"
 }
];

// Tenni tokens → Figma Variables and styles.
// Idempotent: re-running updates existing variables and styles by name.

const MONO_FAMILY = 'Roboto Mono' // ui-monospace has no Figma equivalent

const report = { vars: 0, textStyles: 0, effectStyles: 0, paintStyles: 0, icons: 0, skipped: [] }

// ---------- value parsing ----------

function parseColor(v) {
  v = v.trim()
  let m = v.match(/^#([0-9a-f]{6})$/i)
  if (m) {
    const n = parseInt(m[1], 16)
    return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255, a: 1 }
  }
  m = v.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i)
  if (m) return { r: +m[1] / 255, g: +m[2] / 255, b: +m[3] / 255, a: m[4] === undefined ? 1 : +m[4] }
  return null
}

const px = (v) => {
  const m = String(v).trim().match(/^(-?[\d.]+)(px|ms)?$/)
  return m ? +m[1] : null
}

/** Split on commas that are not inside parentheses. */
function splitTop(v) {
  const parts = []
  let depth = 0
  let cur = ''
  for (const ch of v) {
    if (ch === '(') depth++
    if (ch === ')') depth--
    if (ch === ',' && depth === 0) {
      parts.push(cur.trim())
      cur = ''
    } else cur += ch
  }
  if (cur.trim()) parts.push(cur.trim())
  return parts
}

const aliasOf = (v) => {
  const m = v.trim().match(/^var\(--([\w-]+)\)$/)
  return m ? m[1] : null
}

// ---------- naming ----------

// --c-ball-glow → ball-glow  (palette stays flat, it is hidden from pickers)
const paletteName = (k) => k.replace(/^c-/, '')

// --text-h1-size → text/h1/size, --space-12 → space/12, --r-md → radius/md
function scaleName(k) {
  let m = k.match(/^text-(\w+)-(size|lh|w|ls)$/)
  if (m) return `text/${m[1]}/${{ size: 'size', lh: 'line-height', w: 'weight', ls: 'letter-spacing' }[m[2]]}`
  m = k.match(/^r-(.+)$/)
  if (m) return `radius/${m[1]}`
  const i = k.indexOf('-')
  return i < 0 ? k : `${k.slice(0, i)}/${k.slice(i + 1)}`
}

// --bg-surface-1 → bg/surface-1, --accent → accent/default
function themeName(k) {
  const i = k.indexOf('-')
  return i < 0 ? `${k}/default` : `${k.slice(0, i)}/${k.slice(i + 1)}`
}

function scaleScopes(k) {
  if (k.startsWith('space-')) return ['GAP', 'WIDTH_HEIGHT']
  if (k.startsWith('r-')) return ['CORNER_RADIUS']
  if (/-size$/.test(k)) return ['FONT_SIZE']
  if (/-lh$/.test(k)) return ['LINE_HEIGHT']
  if (/-ls$/.test(k)) return ['LETTER_SPACING']
  if (/-w$/.test(k)) return ['FONT_WEIGHT']
  if (k.startsWith('font-')) return ['FONT_FAMILY']
  if (/^(control|icon|touch|screen|statusbar|appbar|tabbar|home)-/.test(k)) return ['WIDTH_HEIGHT']
  if (k === 'icon-stroke') return ['STROKE_FLOAT']
  return []
}

function themeScopes(k) {
  if (k.startsWith('fg-') || k === 'up' || k === 'down') return ['TEXT_FILL', 'SHAPE_FILL', 'STROKE_COLOR']
  if (k.startsWith('border-')) return ['STROKE_COLOR']
  if (k === 'glass-blur') return ['EFFECT_FLOAT']
  if (k.startsWith('btn-') && k.endsWith('-fg')) return ['TEXT_FILL', 'SHAPE_FILL', 'STROKE_COLOR']
  return ['FRAME_FILL', 'SHAPE_FILL', 'STROKE_COLOR']
}

// ---------- Figma helpers ----------

async function getCollection(name) {
  const all = await figma.variables.getLocalVariableCollectionsAsync()
  return all.find((c) => c.name === name) || figma.variables.createVariableCollection(name)
}

async function getVariable(collection, name, type) {
  const all = await figma.variables.getLocalVariablesAsync(type)
  const found = all.find((v) => v.variableCollectionId === collection.id && v.name === name)
  if (found) return found
  report.vars++
  return figma.variables.createVariable(name, collection, type)
}

function ensureMode(collection, index, name) {
  if (collection.modes[index]) {
    collection.renameMode(collection.modes[index].modeId, name)
    return collection.modes[index].modeId
  }
  return collection.addMode(name)
}

// ---------- 1. palette ----------

async function buildPalette() {
  const col = await getCollection('palette')
  const mode = ensureMode(col, 0, 'Value')
  const byKey = {}
  for (const [k, v] of Object.entries(TOKENS.palette)) {
    const color = parseColor(v)
    if (!color) {
      report.skipped.push(`palette --${k} (gradient/shadow → styles)`)
      continue
    }
    const variable = await getVariable(col, paletteName(k), 'COLOR')
    variable.setValueForMode(mode, color)
    variable.scopes = [] // components use theme tokens only
    variable.hiddenFromPublishing = true
    byKey[k] = variable
  }
  return byKey
}

// ---------- 2. scale ----------

async function buildScale() {
  const col = await getCollection('scale')
  const mode = ensureMode(col, 0, 'Value')
  const byKey = {}
  for (const [k, v] of Object.entries(TOKENS.scale)) {
    let type
    let value
    if (k.startsWith('font-')) {
      type = 'STRING'
      value = k === 'font-mono' ? MONO_FAMILY : v.split(',')[0].replace(/['"]/g, '').trim()
    } else if (k.startsWith('ease-')) {
      report.skipped.push(`scale --${k} (easing: prototype setting, not a variable)`)
      continue
    } else {
      value = px(v)
      if (value === null) {
        report.skipped.push(`scale --${k}: ${v}`)
        continue
      }
      type = 'FLOAT'
    }
    const variable = await getVariable(col, scaleName(k), type)
    variable.setValueForMode(mode, value)
    variable.scopes = scaleScopes(k)
    byKey[k] = variable
  }
  return byKey
}

// ---------- 3. theme (Dark / Light) ----------

// Figma Starter allows one mode per collection. Then Light goes to its own
// collection `theme-light`; on a paid plan a re-run adds the Light mode to
// `theme` and `theme-light` can be deleted.
async function buildTheme(palette) {
  const dark = await getCollection('theme')
  const darkMode = ensureMode(dark, 0, 'Dark')
  let lightMode = null
  try {
    lightMode = ensureMode(dark, 1, 'Light')
  } catch (e) {
    report.skipped.push(`Light mode not allowed on this plan (${e.message}) → collection theme-light`)
  }
  if (lightMode) return fillTheme(dark, { dark: darkMode, light: lightMode }, palette)

  const byKey = await fillTheme(dark, { dark: darkMode }, palette)
  const light = await getCollection('theme-light')
  await fillTheme(light, { light: ensureMode(light, 0, 'Light') }, palette)
  return byKey
}

async function fillTheme(col, modes, palette) {
  const keys = Object.keys(TOKENS.dark)
  const byKey = {}

  const kindOf = (v) => {
    const a = aliasOf(v)
    if (a) return a.startsWith('c-') ? 'COLOR' : 'ALIAS'
    if (parseColor(v)) return 'COLOR'
    if (px(v) !== null) return 'FLOAT'
    return null
  }

  // pass 1: create
  for (const k of keys) {
    let kind = kindOf(TOKENS.dark[k])
    if (kind === 'ALIAS') kind = kindOf(TOKENS.dark[aliasOf(TOKENS.dark[k])])
    if (!kind) continue // gradients and shadows → styles
    const variable = await getVariable(col, themeName(k), kind)
    variable.scopes = themeScopes(k)
    byKey[k] = variable
  }

  // pass 2: values per mode
  for (const [theme, mode] of Object.entries(modes)) {
    for (const k of keys) {
      const variable = byKey[k]
      if (!variable) continue
      const v = TOKENS[theme][k]
      const a = aliasOf(v)
      if (a && palette[a]) variable.setValueForMode(mode, figma.variables.createVariableAlias(palette[a]))
      else if (a && byKey[a]) variable.setValueForMode(mode, figma.variables.createVariableAlias(byKey[a]))
      else if (parseColor(v)) variable.setValueForMode(mode, parseColor(v))
      else if (px(v) !== null) variable.setValueForMode(mode, px(v))
      else report.skipped.push(`theme ${theme} --${k}: ${v}`)
    }
  }

  for (const k of keys) if (!byKey[k]) report.skipped.push(`theme --${k} (gradient/shadow → styles)`)
  return byKey
}

// ---------- 4. text styles ----------

const WEIGHT_STYLE = { 400: 'Regular', 500: 'Medium', 600: 'Semi Bold', 700: 'Bold' }
const norm = (s) => s.toLowerCase().replace(/\s+/g, '')

async function fontFor(family, weight) {
  const fonts = await figma.listAvailableFontsAsync()
  const want = norm(WEIGHT_STYLE[weight] || 'Regular')
  const hit = fonts.find((f) => f.fontName.family === family && norm(f.fontName.style) === want)
  const fontName = hit ? hit.fontName : { family: 'Inter', style: WEIGHT_STYLE[weight] || 'Regular' }
  if (!hit) report.skipped.push(`font ${family} ${weight} not installed → Inter`)
  await figma.loadFontAsync(fontName)
  return fontName
}

async function buildTextStyles(scale) {
  const roles = [...new Set(Object.keys(TOKENS.scale).map((k) => (k.match(/^text-(\w+)-size$/) || [])[1]).filter(Boolean))]
  const displayRoles = ['display', 'h1', 'h2'] // Text.css: these use --font-display
  const existing = await figma.getLocalTextStylesAsync()

  for (const role of roles) {
    const get = (p) => TOKENS.scale[`text-${role}-${p}`]
    const family = role === 'mono' ? MONO_FAMILY : displayRoles.includes(role) ? 'Space Grotesk' : 'Inter'
    const weight = px(get('w'))
    const name = `${role === 'bodysm' ? 'bodySm' : role}`
    let style = existing.find((s) => s.name === name)
    if (!style) {
      style = figma.createTextStyle()
      style.name = name
      report.textStyles++
    }
    style.fontName = await fontFor(family, weight)
    style.fontSize = px(get('size'))
    style.lineHeight = { unit: 'PIXELS', value: px(get('lh')) }
    style.letterSpacing = { unit: 'PIXELS', value: px(get('ls')) }
    if (role === 'caption') style.textCase = 'UPPER'

    for (const [field, p] of [['fontSize', 'size'], ['lineHeight', 'lh'], ['letterSpacing', 'ls']]) {
      const variable = scale[`text-${role}-${p}`]
      if (!variable) continue
      try {
        style.setBoundVariable(field, variable)
      } catch (e) {
        report.skipped.push(`bind ${name}.${field}: ${e.message}`)
      }
    }
  }
}

// ---------- 5. effect styles (shadows) ----------

function parseShadows(v) {
  if (v.trim() === 'none') return []
  return splitTop(v).map((part) => {
    const inset = /\binset\b/.test(part)
    const colorMatch = part.match(/rgba?\([^)]*\)|#[0-9a-f]{6}/i)
    const color = colorMatch ? parseColor(colorMatch[0]) : { r: 0, g: 0, b: 0, a: 1 }
    const nums = part.replace(/inset/, '').replace(colorMatch ? colorMatch[0] : '', '').trim().split(/\s+/).map(px)
    const [x = 0, y = 0, blur = 0, spread = 0] = nums
    const effect = {
      type: inset ? 'INNER_SHADOW' : 'DROP_SHADOW',
      color, offset: { x, y }, radius: blur, spread,
      visible: true, blendMode: 'NORMAL',
    }
    if (!inset) effect.showShadowBehindNode = false // drop shadows only
    return effect
  })
}

async function upsertEffectStyle(name, effects) {
  const existing = await figma.getLocalEffectStylesAsync()
  let style = existing.find((s) => s.name === name)
  if (!style) {
    style = figma.createEffectStyle()
    style.name = name
    report.effectStyles++
  }
  try {
    style.effects = effects
  } catch (e) {
    // Newer API versions require blurType on blurs, older ones reject it.
    const retry = effects.map((ef) => {
      if (ef.type !== 'BACKGROUND_BLUR' && ef.type !== 'LAYER_BLUR') return ef
      const copy = { ...ef }
      if ('blurType' in copy) delete copy.blurType
      else copy.blurType = 'NORMAL'
      return copy
    })
    try {
      style.effects = retry
    } catch {
      report.skipped.push(`effect style ${name}: ${e.message}`)
    }
  }
}

async function buildEffectStyles() {
  for (const theme of ['dark', 'light']) {
    const Theme = theme === 'dark' ? 'Dark' : 'Light'
    for (const [k, v] of Object.entries(TOKENS[theme])) {
      if (!k.startsWith('shadow-') || v === 'none') continue
      await upsertEffectStyle(`${Theme}/${k}`, parseShadows(v))
    }
    await upsertEffectStyle(`${Theme}/glass-blur`, [
      { type: 'BACKGROUND_BLUR', radius: px(TOKENS[theme]['glass-blur']), visible: true },
    ])
  }
  await upsertEffectStyle('Card/shadow-dark', parseShadows(TOKENS.palette['c-card-shadow']))
  await upsertEffectStyle('Card/shadow-light', parseShadows(TOKENS.palette['c-card-shadow-light']))
}

// ---------- 6. paint styles (linear gradients) ----------

function linearGradient(v) {
  const m = v.match(/^linear-gradient\((.*)\)$/)
  if (!m) return null
  const parts = splitTop(m[1])
  const angle = parseFloat(parts.shift()) * Math.PI / 180
  // CSS angle: 0deg points up, clockwise. Figma: gradient runs (0,.5)→(1,.5) in its own space.
  const dx = Math.sin(angle)
  const dy = -Math.cos(angle)
  const L = Math.abs(dx) + Math.abs(dy)
  const a = dx / L, b = dy / L
  const gradientTransform = [
    [a, b, 0.5 - 0.5 * (a + b)],
    [-b, a, 0.5 - 0.5 * (a - b)],
  ]
  const gradientStops = parts.map((s) => {
    const sm = s.match(/^(.+?)\s+([\d.]+)%$/)
    return { color: parseColor(sm[1]), position: +sm[2] / 100 }
  })
  return { type: 'GRADIENT_LINEAR', gradientTransform, gradientStops }
}

async function buildPaintStyles() {
  const sources = [
    ['Card/dark', TOKENS.palette['c-card-dark-bg']],
    ['Card/light', TOKENS.palette['c-card-light-bg']],
  ]
  for (const theme of ['dark', 'light']) {
    const Theme = theme === 'dark' ? 'Dark' : 'Light'
    for (const k of ['phone-bezel', 'phone-screen', 'card-bg']) sources.push([`${Theme}/${k}`, TOKENS[theme][k]])
    report.skipped.push(`${Theme} --bg-ambient (radial backdrop, draw once on the cover frame)`)
  }
  const existing = await figma.getLocalPaintStylesAsync()
  for (const [name, v] of sources) {
    const paint = v && linearGradient(v)
    if (!paint) {
      report.skipped.push(`paint ${name}: ${v}`)
      continue
    }
    let style = existing.find((s) => s.name === name)
    if (!style) {
      style = figma.createPaintStyle()
      style.name = name
      report.paintStyles++
    }
    style.paints = [paint]
  }
}

// ---------- 7. icon components ----------
// One component per icon (not a variant set): instance swap in Figma works
// best with plain components. Color is bound to theme fg/default, so an
// instance recolors by overriding the bound variable.

async function buildIcons(theme) {
  let page = figma.root.children.find((p) => p.name === 'Icons')
  if (!page) {
    page = figma.createPage()
    page.name = 'Icons'
  }
  await page.loadAsync()
  const color = theme['fg-default']
  const bind = (paints) =>
    paints.map((p) => (p.type === 'SOLID' && color ? figma.variables.setBoundVariableForPaint(p, 'color', color) : p))

  let x = 0
  for (const pack of ICON_PACKS) {
    let group = page.children.find((n) => n.type === 'FRAME' && n.name === pack)
    if (!group) {
      group = figma.createFrame()
      group.name = pack
      page.appendChild(group)
    }
    group.layoutMode = 'HORIZONTAL'
    group.layoutWrap = 'WRAP'
    group.primaryAxisSizingMode = 'FIXED'
    group.counterAxisSizingMode = 'AUTO'
    group.resize(24 * 8 + 16 * 7 + 48, group.height)
    group.itemSpacing = 16
    group.counterAxisSpacing = 16
    group.paddingTop = group.paddingBottom = group.paddingLeft = group.paddingRight = 24
    group.fills = []
    group.x = x
    group.y = 0
    x += group.width + 48

    for (const icon of ICONS.filter((i) => i.pack === pack)) {
      const name = `icon/${icon.name}`
      let comp = group.children.find((n) => n.type === 'COMPONENT' && n.name === name)
      if (!comp) {
        comp = figma.createComponent()
        comp.name = name
        group.appendChild(comp)
        report.icons++
      }
      comp.resizeWithoutConstraints(24, 24)
      comp.fills = []
      comp.clipsContent = false
      comp.layoutSizingHorizontal = 'FIXED'
      comp.layoutSizingVertical = 'FIXED'
      comp.description = `${pack} · 24×24, live area 20×20, stroke 1.75. Source: app/src/icons/paths.js`
      for (const child of [...comp.children]) child.remove()

      const svg = figma.createNodeFromSvg(icon.svg)
      for (const child of [...svg.children]) {
        comp.appendChild(child)
        const nodes = 'findAll' in child ? [child, ...child.findAll()] : [child]
        for (const n of nodes) {
          if ('strokes' in n && n.strokes.length) n.strokes = bind(n.strokes)
          if ('fills' in n && Array.isArray(n.fills) && n.fills.length) n.fills = bind(n.fills)
          if ('constraints' in n) n.constraints = { horizontal: 'SCALE', vertical: 'SCALE' }
        }
      }
      svg.remove()
    }
  }
}

// ---------- run ----------

;(async () => {
  try {
    const palette = await buildPalette()
    const scale = await buildScale()
    const theme = await buildTheme(palette)
    await buildTextStyles(scale)
    await buildEffectStyles()
    await buildPaintStyles()
    await buildIcons(theme)
    console.log('Tenni tokens report', report)
    figma.closePlugin(
      `Tenni tokens: +${report.vars} variables, +${report.textStyles} text, ` +
        `+${report.effectStyles} effect, +${report.paintStyles} paint styles, +${report.icons} icons. ` +
        `${report.skipped.length} notes in the console.`,
    )
  } catch (e) {
    console.error(e)
    figma.closePlugin(`Tenni tokens failed: ${e.message}`)
  }
})()
